spring:
  application: palindrome-svc
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create # Change to update after table is created
      format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    name: datsource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: 'postgres'
    password: 'admin'
